package com.zy.zhangyue001.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.NAME
     *
     * @mbg.generated
     */
    private String NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.AGE
     *
     * @mbg.generated
     */
    private Integer AGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID
     *
     * @return the value of student.ID
     *
     * @mbg.generated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param ID the value for student.ID
     *
     * @mbg.generated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.NAME
     *
     * @return the value of student.NAME
     *
     * @mbg.generated
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.NAME
     *
     * @param NAME the value for student.NAME
     *
     * @mbg.generated
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.AGE
     *
     * @return the value of student.AGE
     *
     * @mbg.generated
     */
    public Integer getAGE() {
        return AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.AGE
     *
     * @param AGE the value for student.AGE
     *
     * @mbg.generated
     */
    public void setAGE(Integer AGE) {
        this.AGE = AGE;
    }
}