package com.zy.zhangyue001.req;

import lombok.Data;

@Data
public class StudentRequest {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.id
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.name
     *
     * @mbg.generated
     */
    private String NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sex
     *
     * @mbg.generated
     */
    private Integer AGE;
}
