package com.zy.zhangyue001.req;

import lombok.Data;

@Data
public class StuRequest {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sex
     *
     * @mbg.generated
     */
    private String sex;
}
